In [ ]:
import pandas as pd
import csv
import numpy as np

In [ ]:
final_df = pd.read_csv('parking_analysed.csv')
final_df.head()

,Unnamed: 0,Name,parking_id,latitude,longitude,Apartments_nearby,charging_station_nearby,Food_court_nearby,Gas_station_nearby,Malls_nearby,WARD_NO,FREQ,Url
0,0,BBMP Parking Space,ChIJ_ai2SuYVrjsRYEPrdzFxh7E,12.956836,77.581783,6,14,5,3,10,158,452,https://www.google.com/maps/place/?q=place_id:...
1,1,Shanti Nagar parking,ChIJWaLM37AVrjsRivlbh9NwR0o,12.954053,77.591901,7,23,5,4,12,102,420,https://www.google.com/maps/place/?q=place_id:...
2,2,BDA Complex Parking,ChIJ7VYXtlsUrjsRXghoSce9Cfw,12.930442,77.622537,8,17,13,3,7,157,427,https://www.google.com/maps/place/?q=place_id:...
3,3,HAL parking lot,ChIJuccM0rMWrjsRhgG0RP5Cn0c,12.984170,77.648606,5,6,6,2,7,89,498,https://www.google.com/maps/place/?q=place_id:...
4,4,Unity Building Parking Lot,ChIJfQCQsN8VrjsRTmw40xo6hAY,12.964654,77.586791,6,16,6,3,14,140,409,https://www.google.com/maps/place/?q=place_id:...

In [ ]:
def charging_algo(final_df):
  final_df['min'] = final_df['charging_station_nearby'] + final_df['FREQ']*10
  final_df['rest'] = final_df['Food_court_nearby']*5 + final_df['Gas_station_nearby']*10 + final_df['Malls_nearby']*5 + final_df['Apartments_nearby']*10 
  final_df['final_point'] = final_df['min'] + final_df['rest']

charging_algo(final_df)

In [ ]:
final_df.head()

,Unnamed: 0,Name,parking_id,latitude,longitude,Apartments_nearby,charging_station_nearby,Food_court_nearby,Gas_station_nearby,Malls_nearby,WARD_NO,FREQ,Url,min,rest,final_point
0,0,BBMP Parking Space,ChIJ_ai2SuYVrjsRYEPrdzFxh7E,12.956836,77.581783,6,14,5,3,10,158,452,https://www.google.com/maps/place/?q=place_id:...,4534,165,4699
1,1,Shanti Nagar parking,ChIJWaLM37AVrjsRivlbh9NwR0o,12.954053,77.591901,7,23,5,4,12,102,420,https://www.google.com/maps/place/?q=place_id:...,4223,195,4418
2,2,BDA Complex Parking,ChIJ7VYXtlsUrjsRXghoSce9Cfw,12.930442,77.622537,8,17,13,3,7,157,427,https://www.google.com/maps/place/?q=place_id:...,4287,210,4497
3,3,HAL parking lot,ChIJuccM0rMWrjsRhgG0RP5Cn0c,12.984170,77.648606,5,6,6,2,7,89,498,https://www.google.com/maps/place/?q=place_id:...,4986,135,5121
4,4,Unity Building Parking Lot,ChIJfQCQsN8VrjsRTmw40xo6hAY,12.964654,77.586791,6,16,6,3,14,140,409,https://www.google.com/maps/place/?q=place_id:...,4106,190,4296

In [ ]:
print("Mean:Computed column-wise:");

meanData = final_df['final_point'].mean();

print(meanData);

print("Median:Computed column-wise:");

medianData = final_df['final_point'].median();

print(medianData);

print("Mode:Computed column-wise:");

modeData = final_df['final_point'].mode();

print(modeData);

Mean:Computed column-wise:
4374.516666666666
Median:Computed column-wise:
4600.5
Mode:Computed column-wise:
0    4591
1    4628
2    4632
3    4646
dtype: int64

In [ ]:
final_df = final_df.sort_values(by=['final_point'])

In [ ]:
final_df.head()
# final_df.to_csv('final_point_result.csv')

,Unnamed: 0,Name,parking_id,latitude,longitude,Apartments_nearby,charging_station_nearby,Food_court_nearby,Gas_station_nearby,Malls_nearby,WARD_NO,FREQ,Url,min,rest,final_point
58,58,Baiyappanahalli Parking Backside,ChIJPRA7RfkXrjsRKvPCWRxh02o,12.991535,77.651593,6,4,3,1,7,63,201,https://www.google.com/maps/place/?q=place_id:...,2014,120,2134
57,57,Car Parking,ChIJ5cqvSGgWrjsRDhn6jJxwacA,12.988043,77.594139,3,17,6,3,11,72,267,https://www.google.com/maps/place/?q=place_id:...,2687,145,2832
56,56,Rezervd Smart Parking,ChIJLcMrT2EXrjsR8p_y13XhLIg,12.997325,77.600769,6,12,5,3,11,60,288,https://www.google.com/maps/place/?q=place_id:...,2892,170,3062
55,55,Parking Lot,ChIJbeqOUMEVrjsRm9YXc820njg,12.949516,77.589941,7,25,6,6,10,119,305,https://www.google.com/maps/place/?q=place_id:...,3075,210,3285
53,53,PES Car Parking,ChIJHfqhck8_rjsRaQkGXLJMzFc,12.934831,77.534468,0,2,1,6,2,37,342,https://www.google.com/maps/place/?q=place_id:...,3422,75,3497

In [ ]:
minvalue = final_df['final_point'].min()
maxvalue = final_df['final_point'].max()
  
minvalue , maxvalue

(2134, 5121)

## GRADE

In [ ]:
def grade_station(dl):
    if minvalue <= dl <= minvalue+1000: return 1
    elif minvalue+1000 < dl <= minvalue+1500: return 2
    elif minvalue+1500 < dl <= minvalue+1800: return 3
    elif minvalue+1800 < dl <= minvalue+2000: return 4
    elif minvalue+2000 < dl <= minvalue+2200: return 5
    elif minvalue+2200 < dl <= minvalue+2400: return 6
    elif minvalue+2400 < dl <= minvalue+2600: return 7
    elif minvalue+2600 < dl <= minvalue+2800: return 8
    elif minvalue+2800 < dl <= minvalue+2900: return 9
    elif minvalue+2900 < dl <= minvalue+3000: return 10
    else: return 'None'

final_df["grade"] = final_df['final_point'].map(grade_station)

In [ ]:
final_df.head()

,Unnamed: 0,Name,parking_id,latitude,longitude,Apartments_nearby,charging_station_nearby,Food_court_nearby,Gas_station_nearby,Malls_nearby,WARD_NO,FREQ,Url,chg_den,min,rest,final_point,grade
58,58,Baiyappanahalli Parking Backside,ChIJPRA7RfkXrjsRKvPCWRxh02o,12.991535,77.651593,6,4,3,1,7,63,201,https://www.google.com/maps/place/?q=place_id:...,0.019900,2014,120,2134,1
57,57,Car Parking,ChIJ5cqvSGgWrjsRDhn6jJxwacA,12.988043,77.594139,3,17,6,3,11,72,267,https://www.google.com/maps/place/?q=place_id:...,0.063670,2687,145,2832,1
56,56,Rezervd Smart Parking,ChIJLcMrT2EXrjsR8p_y13XhLIg,12.997325,77.600769,6,12,5,3,11,60,288,https://www.google.com/maps/place/?q=place_id:...,0.041667,2892,170,3062,1
55,55,Parking Lot,ChIJbeqOUMEVrjsRm9YXc820njg,12.949516,77.589941,7,25,6,6,10,119,305,https://www.google.com/maps/place/?q=place_id:...,0.081967,3075,210,3285,2
53,53,PES Car Parking,ChIJHfqhck8_rjsRaQkGXLJMzFc,12.934831,77.534468,0,2,1,6,2,37,342,https://www.google.com/maps/place/?q=place_id:...,0.005848,3422,75,3497,2

In [ ]:
deselectlist =[ 'Apartments_nearby', 'charging_station_nearby' , 'Food_court_nearby' ,'Gas_station_nearby','Malls_nearby','FREQ','chg_den','min','rest']
selectlist =[x for x in final_df.columns if x not in deselectlist]
datatowrite = final_df[selectlist]
datatowrite.to_csv('final.csv')